# Generated by Django 5.2.8 on 2025-11-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
